### ISSUE TITLE
pubish_camera(data) not working

### ISSUE THREAD

**Issue by wmrifenb** [team-inrs/CarND-Capstone#10]
Has anyone gotten the following error when running the capstone sim with a docker container and found out what the cause was?

message handler error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/engineio/server.py", line 398, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 509, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 448, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 451, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python2.7/dist-packages/socketio/server.py", line 480, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "/capstone/ros/src/styx/server.py", line 58, in image
    bridge.publish_camera(data)
  File "/capstone/ros/src/styx/bridge.py", line 180, in publish_camera
    image_message = self.bridge.cv2_to_imgmsg(image_array, encoding="rgb8")
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/cv_bridge/core.py", line 248, in cv2_to_imgmsg
    img_msg.height = cvim.shape[0]
IndexError: tuple index out of range

This is also an issue on the udacity repo:
[https://github.com/udacity/CarND-Capstone/issues/107](url)

**Comment by wmrifenb** [comment]
I found the solution here:
https://discussions.udacity.com/t/capstone-project-message-error-image-publisher/401756/16

Basically pillow should be updated. To solve, in your docker container enter:

$ pip uninstall pillow
$ pip install pillow

pip will uninstall pillow 2.2 and then install pillow 4.3

I will modify the docker file so we dont have to to this though
