### ISSUE TITLE
IndexError in waypoint_updater.py

### ISSUE THREAD

**Issue by adattudos** [team-inrs/CarND-Capstone#60]
924409_site.log produced during the Carla run shows the following error:
```
Traceback (most recent call last):
  File "/home/udacity/Git/carnd_cap_autogradr/submissions/924409/ros/src/waypoint_updater/waypoint_updater.py", line 292, in <module>
    WaypointUpdater()
  File "/home/udacity/Git/carnd_cap_autogradr/submissions/924409/ros/src/waypoint_updater/waypoint_updater.py", line 114, in __init__
    this_distance = self.distance_to_position(waypoints, i, self.all_waypoints[self.traffic_light_waypoint_index].pose.pose.position)
IndexError: list index out of range
[waypoint_updater-4] process has died
```

**Comment by tanyt81** [comment]
In the simulator, the index of the closest waypoint to the incoming traffic light is broadcast via  /traffic_waypoint topic, apparently it is not doing so in Carla (according to the bag file). 

I guessed we have to use "waypoint" filed in the message broadcast by tl_detector instead. I have no way of testing and examining that particular message in the bag file as I cant even compile without cuda. 

Anyone can help ?
